
POST    http://localhost:3000/v1/movies

 {
  "title": "The Shawshank Redemption",
  "year": 1994,
  "runtime": "142 minutes",
  "genres": ["Drama", "Prison"]
}

###
GET http://localhost:3000/v1/movies/1