
POST    http://localhost:3000/v1/movies

 {
  "title": "The Shawshank Redemption",
  "year": 1900,
  "runtime": 142,
  "genres": ["Drama", "Prison"]
}

###
GET http://localhost:3000/v1/movies/8



###
PATCH    http://localhost:3000/v1/movies/2

 {
  "title": "The Shawshank Redemption",
  "year": 1896,
  "runtime": 143,
  "genres": ["Drama", "Prison"]
}

###
DELETE  http://localhost:3000/v1/movies/10


###
GET http://localhost:3000/v1/movies?title=godfather&genres=crime,drama&page=2&page_size=1&sort=-id
