
POST    http://localhost:3000/v1/movies

 {
  "title": "The Shawshank Redemption",
  "year": 1900,
  "runtime": 142,
  "genres": ["Drama", "Prison"]
}

###
GET http://localhost:3000/v1/movies/1



###
PATCH    http://localhost:3000/v1/movies/2

 {
  "title": "The Shawshank Redemption",
  "year": 100,
  "runtime": 143,
  "genres": ["Drama", "Prison"]
}

###
DELETE  http://localhost:3000/v1/movies/1


