
POST    http://localhost:3000/v1/users
 
 {
  "name": "Kaka",
  "email": "test11@example.com",
  "password": "pas55dword"
}

###

PUT    http://localhost:3000/v1/users/activate

{
  "token": "6WVXZ2AA3KYQZ6IXV564VHH25M"
}
###

POST    http://localhost:3000/v1/tokens/authentication

{
  "email": "test5@example.com",
  "password": "pas55dword"
}
