name: "Setup Environment"
description: "Sets up the environment by checking out code, setting up Go, and installing Task CLI."
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: stable
        cache: false

    - name: Install Task CLI
      uses: arduino/setup-task@v2
      with:
        version: 3.x
