name: CI Pipeline

on: push

jobs:
  lint:
    name: Lint Application
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Install GolangCI-Lint
        run: task instal-golangci-lint
      - name: Run Lint
        run: task lint

  test:
    name: Test Application
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Run Test
        run: task test

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Build
        run: task build
      - name: Copy Files
        run: |
          mkdir artifacts
          cp bin/linux_amd64/api artifacts/.
      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: artifacts
