name: CI Checks

on: push
jobs:
  lint:
    name: Lint Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version:  stable
          cache: false
      - uses: arduino/setup-task@v2
      - run: task instal-golangci-lint
      - name: Run Lint
        run: task lint

  test:
    name: Test Application
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version:  stable
          cache: false
      - uses: arduino/setup-task@v2
    
      - name: Run Test
        run: task test

  build:
    name: Build App
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version:  stable
          cache: false
      - uses: arduino/setup-task@v2
    
      - name: Build
        run: task build

      - name: Copy Files
        run: |
          mkdir artifacts
          cp bin/linux_amd64/api artifacts/.
      
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: artifacts