name: CI Pipeline

on: push

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Install Task CLI
        run: |
          sudo sh -c "curl -s https://taskfile.dev/install.sh | sh"
          sudo mv ./bin/task /usr/local/bin/task

  lint:
    name: Lint Application
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install GolangCI-Lint
        run: task instal-golangci-lint
      - name: Run Lint
        run: task lint

  test:
    name: Test Application
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Run Test
        run: task test

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build
        run: task build

      - name: Copy Files
        run: |
          mkdir artifacts
          cp bin/linux_amd64/api artifacts/.

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: artifacts
